/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.Datas;
import model.bean.Excel;
import model.bean.Impressoes;
import model.bean.Pessoa;
import model.bean.SomenteNumeros;
import model.dao.ImpressoesDAO;
import model.dao.PessoaDAO;

/**
 *
 * @author Camara
 */
public class TelaRelatorioImpressoes extends javax.swing.JDialog {

    /**
     * Creates new form TelaRelatorioImpressoes
     */
    public TelaRelatorioImpressoes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        txtMesRelat.setDocument(new SomenteNumeros());

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMesRelat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        jLabel1.setText("Relatório de Impressões");

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Informe o mês :");

        txtMesRelat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jButton1.setText("Gerar Relatório");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 2, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("*Apenas números de 01 - 12");

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("O relatório mensal informará todas as Impressões de todas as pessoas cadastradas que constam no mês solicitado.");

        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("* Este relatório poderá demorar alguns segundos.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(113, 113, 113)
                                .addComponent(txtMesRelat, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel4)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMesRelat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(55, 55, 55)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jTabbedPane4.addTab("Relatório Mensal", jPanel1);

        jButton2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jButton2.setText("Gerar Relatório Total ");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("O relatório total informará todas as Impressões de todas as pessoas cadastradas que constam no banco de dados.");

        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("* Este relatório poderá demorar alguns minutos.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(325, 325, 325))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jTabbedPane4.addTab("Relatório Total", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Datas data1 = new Datas();
        
        String nomeMesTransf = data1.transformaMesNome(Integer.parseInt(txtMesRelat.getText()));
        String qualReatorio = "Relatorio Impressões do Mês de " + nomeMesTransf + " - ";
        String mesRelat = txtMesRelat.getText();
        String titleArquivo = data1.getDataHora();
        if(mesRelat.length() > 0)
        {
            //Abastece a classe Excel
            Excel excel = new Excel();
            excel.setTitulo("Relatório Mensal - " + nomeMesTransf);
            excel.setQualRelatorio(qualReatorio);
            excel.setDataHora(titleArquivo);
            
                //Buscando os IDS que estão no banco de impressoes e colocando em um array
                ImpressoesDAO impressoes = new ImpressoesDAO();
                Impressoes impre = new Impressoes();
                
                impre.setDataInicialRelat(txtMesRelat.getText());
                impre.setDataFinalRelat(txtMesRelat.getText());

                List <Impressoes> resultBusca = impressoes.buscaTodosIds(impre);
                ArrayList <Integer> idImpre = new ArrayList<Integer>();
                Set<Integer> set = new HashSet<>();
                for(Impressoes imp:resultBusca)
                {
                    idImpre.add(imp.getIdPerfil());
                }

                for(int a: idImpre)
                {
                    set.add(a);
                }        

                //Agora vou passar todos os IDS
                PessoaDAO pessoas = new PessoaDAO();
                Pessoa pes = new Pessoa();
                
                excel.setTotalDeIds(set.size());
                
                String[] nome = new String[set.size()];
                String[] cpf = new String[set.size()];
                String[] cidade = new String[set.size()];
                String[] estado = new String[set.size()];
                int[] quatdade = new int[set.size()];
                int quatadeTotal = 0;

                for(int i = 0; i < set.size(); i++)
                {
                    pes.setId((int) set.toArray()[i]);
                    impre.setId((int) set.toArray()[i]);
                    impre.setDataInicialRelat(txtMesRelat.getText());
                    impre.setDataFinalRelat(txtMesRelat.getText());
                    List <Pessoa> resu = pessoas.buscaId(pes);
                    

                    for(Pessoa pess:resu)
                    {
                        nome[i] = pess.getNome();
                        cpf[i]  = pess.getCpf();
                        cidade[i] = pess.getCidade();
                        estado[i] = pess.getEstado();
                        quatdade[i] = impressoes.buscaQuantidadeImpressoesRelatorio(impre);
                    }
                }
                
                excel.setTamanhoArray(set.size());
                
                excel.setNome(nome);
                excel.setCpf(cpf);
                excel.setCidade(cidade);
                excel.setEstado(estado);
                excel.setQuatdade(quatdade);
                
                
                for(int zver = 0; zver < quatdade.length; zver++)
                {
                    quatadeTotal += quatdade[zver];
                }
                
                excel.setQuatdadeTotal(quatadeTotal);
            //Aqui eu construo o Excel    
            try {
                excel.CriaRelatorioImpreMensal();
                Object[] options = {"Sim","Não"};
                int dialogR = JOptionPane.showOptionDialog(null,
                    "Planilha gerada com Sucesso, deseja abrir o diretório ?",
                    System.getProperty("user.dir"),
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,     //do not use a custom Icon
                    options,  //the titles of buttons
                    options[0]); //default button title
                if(dialogR == JOptionPane.YES_OPTION)
                {
                    String dir = System.getProperty("user.dir");
                    dir.replace("\\\\\\\\\\", "/");
                    try {
                    Runtime.getRuntime().exec("explorer " + dir + "\\Relatorios");
                    } catch (IOException ex) {
                    Logger.getLogger(TelaRelatorioImpressoes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                        } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioImpressoes.class.getName()).log(Level.SEVERE, null, ex);
            }
                /*try {
                Runtime.getRuntime().exec("explorer C:/Users/Camara/Documents/");
                } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioImpressoes.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                File arquivo = new File("C:/Users/Camara/Downloads/brasão.png");
                
                //Abrindo Arquivo
                Desktop desktop = Desktop.getDesktop();
                try {  
                desktop.open(arquivo);
                } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioImpressoes.class.getName()).log(Level.SEVERE, null, ex);
                }*/

        }
        else
        {
            JOptionPane.showMessageDialog(null, "Favor informar o mês para gerar o relatório.", "UNDEFINED", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Datas data1 = new Datas();
        
        String qualReatorio = "Relatório de Impressões Total - ";
        String titleArquivo = data1.getDataHora();

            //Abastece a classe Excel
            Excel excel = new Excel();
            excel.setTitulo("Relatório Total");
            excel.setQualRelatorio(qualReatorio);
            excel.setDataHora(titleArquivo);
            
                //Buscando os IDS que estão no banco de impressoes e colocando em um array
                ImpressoesDAO impressoes = new ImpressoesDAO();
                Impressoes impre = new Impressoes();

                List <Impressoes> resultBusca = impressoes.buscaTodosIdsTotal(impre);
                ArrayList <Integer> idImpre = new ArrayList<Integer>();
                Set<Integer> set = new HashSet<>();
                for(Impressoes imp:resultBusca)
                {
                    idImpre.add(imp.getIdPerfil());
                }

                for(int a: idImpre)
                {
                    set.add(a);
                }        

                //Agora vou passar todos os IDS
                PessoaDAO pessoas = new PessoaDAO();
                Pessoa pes = new Pessoa();
                
                excel.setTotalDeIds(set.size());
                
                String[] nome = new String[set.size()];
                String[] cpf = new String[set.size()];
                String[] cidade = new String[set.size()];
                String[] estado = new String[set.size()];
                int[] quatdade = new int[set.size()];
                int quatadeTotal = 0;

                for(int i = 0; i < set.size(); i++)
                {
                    pes.setId((int) set.toArray()[i]);
                    impre.setId((int) set.toArray()[i]);
                    List <Pessoa> resu = pessoas.buscaId(pes);
                    

                    for(Pessoa pess:resu)
                    {
                        nome[i] = pess.getNome();
                        cpf[i]  = pess.getCpf();
                        cidade[i] = pess.getCidade();
                        estado[i] = pess.getEstado();
                        quatdade[i] = impressoes.buscaQuantidadeImpressoesTotalRelatorio(impre);
                    }
                }
                
                excel.setTamanhoArray(set.size());
                
                excel.setNome(nome);
                excel.setCpf(cpf);
                excel.setCidade(cidade);
                excel.setEstado(estado);
                excel.setQuatdade(quatdade);
                
                
                for(int zver = 0; zver < quatdade.length; zver++)
                {
                    quatadeTotal += quatdade[zver];
                }
                
                excel.setQuatdadeTotal(quatadeTotal);
            //Aqui eu construo o Excel    
            try {
                excel.CriaRelatorioImpreTotal();
                Object[] options = {"Sim","Não"};
                int dialogR = JOptionPane.showOptionDialog(null,
                    "Planilha gerada com Sucesso, deseja abrir o diretório ?",
                    System.getProperty("user.dir"),
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,     //do not use a custom Icon
                    options,  //the titles of buttons
                    options[0]); //default button title
                if(dialogR == JOptionPane.YES_OPTION)
                {
                    String dir = System.getProperty("user.dir");
                    dir.replace("\\\\\\\\\\", "/");
                    try {
                    Runtime.getRuntime().exec("explorer " + dir + "\\Relatorios");
                    } catch (IOException ex) {
                    Logger.getLogger(TelaRelatorioImpressoes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                        } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioImpressoes.class.getName()).log(Level.SEVERE, null, ex);
            }
                /*try {
                Runtime.getRuntime().exec("explorer C:/Users/Camara/Documents/");
                } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioImpressoes.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                File arquivo = new File("C:/Users/Camara/Downloads/brasão.png");
                
                //Abrindo Arquivo
                Desktop desktop = Desktop.getDesktop();
                try {  
                desktop.open(arquivo);
                } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioImpressoes.class.getName()).log(Level.SEVERE, null, ex);
                }*/

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioImpressoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioImpressoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioImpressoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioImpressoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaRelatorioImpressoes dialog = new TelaRelatorioImpressoes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField txtMesRelat;
    // End of variables declaration//GEN-END:variables
}
