/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.bean.Datas;
import model.bean.Impressoes;
import model.bean.Limites;
import model.bean.SomenteNumeros;
import model.bean.clsDados;
import model.dao.ImpressoesDAO;
import model.dao.LimitesDAO;

/**
 *
 * @author Camara
 */
public class TelaEditaImpressoes extends javax.swing.JDialog {

    /**
     * Creates new form TelaEditaImpressoes
     */
    public TelaEditaImpressoes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtqtdadeImpre.setDocument(new SomenteNumeros());
        this.setResizable(false);
        
        clsDados clsDados1 = new clsDados();
        int idTable = clsDados1.getIdTable();
        
        //IMPRESSOES
        ImpressoesDAO impressoes = new ImpressoesDAO();
        Impressoes im = new Impressoes();
        
        im.setId(idTable);
        int qtdadeImpressoes = impressoes.buscaQuantidadeImpressoes(im);
        lblqtdadeImpre.setText(Integer.toString(qtdadeImpressoes));
        
        //Datas
        Datas datas = new Datas();
        String dataAtual = datas.getDataAtualHueBr();
        lblDataAtual.setText(dataAtual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblqtdadeImpre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtqtdadeImpre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblDataAtual = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Quantidade de Impressões Realizadas:");

        lblqtdadeImpre.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        lblqtdadeImpre.setForeground(new java.awt.Color(102, 102, 102));

        jLabel2.setText("Quantidade de Impressões à realizar:");

        jLabel3.setText("Data Atual:");

        lblDataAtual.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N

        jButton1.setText("Adicionar Impressão");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover Impressão");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDataAtual))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtqtdadeImpre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblqtdadeImpre)))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblqtdadeImpre))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtqtdadeImpre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDataAtual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clsDados clsDados1 = new clsDados();
        int idTable = clsDados1.getIdTable();
        
        String qtdadeImp = txtqtdadeImpre.getText();

        Datas datas1 = new Datas();
        String dataAtual = datas1.getDataAtual();

        ImpressoesDAO impressoes1 = new ImpressoesDAO();
        Impressoes im1 = new Impressoes();

        LimitesDAO limites1 = new LimitesDAO();
        Limites li1 = new Limites();

        int limiteImpre = limites1.buscaLimiteImpre(li1);
        
        if(qtdadeImp.length() > 0)
        {
            im1.setId(idTable);
            int qtdadeImpres = impressoes1.buscaQuantidadeImpressoes(im1);

            if(qtdadeImpres >= limiteImpre)
            {
                JOptionPane.showMessageDialog(null, "O usuário já realizou todas as impressões disponíveis", "Limite Excedido de " + limiteImpre + " impressões", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                int totalQuantdadeImpre = Integer.parseInt(qtdadeImp) + qtdadeImpres;

                if(totalQuantdadeImpre > limiteImpre)
                {
                    JOptionPane.showMessageDialog(null, "O valor informado ultrapassa o limite de impressões. Gentileza informar outro valor.", "Limite Excedido de " + limiteImpre + " impressões", JOptionPane.WARNING_MESSAGE);
                }
                else
                {
                    im1.setQtdadeImpre(Integer.parseInt(qtdadeImp));
                    im1.setDataImpre(dataAtual);
                    im1.setIdPerfil(idTable);
                    impressoes1.create(im1);
                    this.dispose();
                    
                    TelaVerificaEdita telaVerificaEdita = new TelaVerificaEdita(null, rootPaneCheckingEnabled);
                    telaVerificaEdita.setVisible(true);
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Favor informar uma quantidade válida");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clsDados clsDados1 = new clsDados();
        int idTable = clsDados1.getIdTable();
        
        ImpressoesDAO impressoes1 = new ImpressoesDAO();
        Impressoes im1 = new Impressoes();
        
        im1.setIdPerfil(idTable);
        int ultimoIdImpre = impressoes1.buscaUltimoIdImpressao(im1);
        
        if(ultimoIdImpre > 0)
        {
            im1.setId(ultimoIdImpre);
            impressoes1.deletaImpre(im1);
            this.dispose();
            
            TelaVerificaEdita telaVerificaEdita = new TelaVerificaEdita(null, rootPaneCheckingEnabled);
            telaVerificaEdita.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Não existem impressões realizadas !");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditaImpressoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditaImpressoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditaImpressoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditaImpressoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaEditaImpressoes dialog = new TelaEditaImpressoes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDataAtual;
    private javax.swing.JLabel lblqtdadeImpre;
    private javax.swing.JTextField txtqtdadeImpre;
    // End of variables declaration//GEN-END:variables
}
