/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.Datas;
import model.bean.Excel;
import model.bean.Ligacoes;
import model.bean.Pessoa;
import model.bean.SomenteNumeros;
import model.dao.LigacoesDAO;
import model.dao.PessoaDAO;

/**
 *
 * @author Camara
 */
public class TelaRelatorioLigacoes extends javax.swing.JDialog {

    /**
     * Creates new form TelaRelatorioLigacoes
     */
    public TelaRelatorioLigacoes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        txtMesRelat.setDocument(new SomenteNumeros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtMesRelat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        jLabel1.setText("Relatório de Ligações");

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("O relatório mensal informará todas as Ligações de todas as pessoas cadastradas que constam no mês solicitado.");

        jButton1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jButton1.setText("Gerar Relatório");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel4.setText("Informe o mês:");

        txtMesRelat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 2, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("*Apenas números de 01-12");

        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("* Este relatório poderá demorar alguns segundos.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMesRelat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMesRelat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Relatório Mensal", jPanel1);

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("O relatório total informará todas as Impressões de todas as pessoas cadastradas que constam no banco de dados.");

        jButton2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jButton2.setText("Gerar Relatório Total");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("* Este relatório poderá demorar alguns minutos.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel7)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addGap(67, 67, 67)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Relatório Total", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Datas data1 = new Datas();
        
        String nomeMesTransf = data1.transformaMesNome(Integer.parseInt(txtMesRelat.getText()));
        String qualReatorio = "Relatorio Ligações do Mês de " + nomeMesTransf + " - ";
        String mesRelat = txtMesRelat.getText();
        String titleArquivo = data1.getDataHora();
        if(mesRelat.length() > 0)
        {
            //Abastece a classe Excel
            Excel excel = new Excel();
            excel.setTitulo("Relatório Mensal - " + nomeMesTransf);
            excel.setQualRelatorio(qualReatorio);
            excel.setDataHora(titleArquivo);
            
                //Buscando os IDS que estão no banco de impressoes e colocando em um array
                LigacoesDAO ligas = new LigacoesDAO();
                Ligacoes l = new Ligacoes();
                
                l.setDataInicialRelat(txtMesRelat.getText());
                l.setDataFinalRelat(txtMesRelat.getText());

                List <Ligacoes> resultBusca = ligas.buscaTodosIds(l);
                ArrayList <Integer> idLiga = new ArrayList<Integer>();
                Set<Integer> set = new HashSet<>();
                for(Ligacoes imp:resultBusca)
                {
                    idLiga.add(imp.getIdPerfil());
                }

                for(int a: idLiga)
                {
                    set.add(a);
                }        

                //Agora vou passar todos os IDS
                PessoaDAO pessoas = new PessoaDAO();
                Pessoa pes = new Pessoa();
                
                excel.setTotalDeIds(set.size());
                
                String[] nome = new String[set.size()];
                String[] cpf = new String[set.size()];
                String[] cidade = new String[set.size()];
                String[] estado = new String[set.size()];
                int[] quatdade = new int[set.size()];
                int quatadeTotal = 0;

                for(int i = 0; i < set.size(); i++)
                {
                    pes.setId((int) set.toArray()[i]);
                    l.setId((int) set.toArray()[i]);
                    l.setDataInicialRelat(txtMesRelat.getText());
                    l.setDataFinalRelat(txtMesRelat.getText());
                    List <Pessoa> resu = pessoas.buscaId(pes);
                    

                    for(Pessoa pess:resu)
                    {
                        nome[i] = pess.getNome();
                        cpf[i]  = pess.getCpf();
                        cidade[i] = pess.getCidade();
                        estado[i] = pess.getEstado();
                        quatdade[i] = ligas.buscaQuantidadeLigacoesRelatorio(l);
                    }
                }
                
                excel.setTamanhoArray(set.size());
                
                excel.setNome(nome);
                excel.setCpf(cpf);
                excel.setCidade(cidade);
                excel.setEstado(estado);
                excel.setQuatdade(quatdade);
                
                for(int zver = 0; zver < quatdade.length; zver++)
                {
                    quatadeTotal += quatdade[zver];
                }
                
                excel.setQuatdadeTotal(quatadeTotal);
                
            //Aqui eu construo o Excel    
            try {
                excel.CriaRelatorioLigaMensal();
                Object[] options = {"Sim","Não"};
                int dialogR = JOptionPane.showOptionDialog(null,
                    "Planilha gerada com Sucesso, deseja abrir o diretório ?",
                    System.getProperty("user.dir"),
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,     //do not use a custom Icon
                    options,  //the titles of buttons
                    options[0]); //default button title
                if(dialogR == JOptionPane.YES_OPTION)
                {
                    String dir = System.getProperty("user.dir");
                    dir.replace("\\\\\\\\\\", "/");
                    try {
                    Runtime.getRuntime().exec("explorer " + dir + "\\Relatorios");
                    } catch (IOException ex) {
                    Logger.getLogger(TelaRelatorioLigacoes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                        } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioLigacoes.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        else
        {
            JOptionPane.showMessageDialog(null, "Favor informar o mês para gerar o relatório.", "UNDEFINED", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                Datas data1 = new Datas();
        
        String qualReatorio = "Relatorio Ligações Total - ";
        String titleArquivo = data1.getDataHora();
            //Abastece a classe Excel
            Excel excel = new Excel();
            excel.setTitulo("Relatório Total");
            excel.setQualRelatorio(qualReatorio);
            excel.setDataHora(titleArquivo);
            
                //Buscando os IDS que estão no banco de impressoes e colocando em um array
                LigacoesDAO ligas = new LigacoesDAO();
                Ligacoes l = new Ligacoes();

                List <Ligacoes> resultBusca = ligas.buscaTodosIdsTotal(l);
                ArrayList <Integer> idLiga = new ArrayList<Integer>();
                Set<Integer> set = new HashSet<>();
                for(Ligacoes imp:resultBusca)
                {
                    idLiga.add(imp.getIdPerfil());
                }

                for(int a: idLiga)
                {
                    set.add(a);
                }        

                //Agora vou passar todos os IDS
                PessoaDAO pessoas = new PessoaDAO();
                Pessoa pes = new Pessoa();
                
                excel.setTotalDeIds(set.size());
                
                String[] nome = new String[set.size()];
                String[] cpf = new String[set.size()];
                String[] cidade = new String[set.size()];
                String[] estado = new String[set.size()];
                int[] quatdade = new int[set.size()];
                int quatadeTotal = 0;

                for(int i = 0; i < set.size(); i++)
                {
                    pes.setId((int) set.toArray()[i]);
                    l.setId((int) set.toArray()[i]);
                    List <Pessoa> resu = pessoas.buscaId(pes);
                    

                    for(Pessoa pess:resu)
                    {
                        nome[i] = pess.getNome();
                        cpf[i]  = pess.getCpf();
                        cidade[i] = pess.getCidade();
                        estado[i] = pess.getEstado();
                        quatdade[i] = ligas.buscaQuantidadeLigacoesTotalRelatorio(l);
                    }
                }
                
                excel.setTamanhoArray(set.size());
                
                excel.setNome(nome);
                excel.setCpf(cpf);
                excel.setCidade(cidade);
                excel.setEstado(estado);
                excel.setQuatdade(quatdade);
                
                for(int zver = 0; zver < quatdade.length; zver++)
                {
                    quatadeTotal += quatdade[zver];
                }
                
                excel.setQuatdadeTotal(quatadeTotal);
                
            //Aqui eu construo o Excel    
            try {
                excel.CriaRelatorioLigaTotal();
                Object[] options = {"Sim","Não"};
                int dialogR = JOptionPane.showOptionDialog(null,
                    "Planilha gerada com Sucesso, deseja abrir o diretório ?",
                    System.getProperty("user.dir"),
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,     //do not use a custom Icon
                    options,  //the titles of buttons
                    options[0]); //default button title
                if(dialogR == JOptionPane.YES_OPTION)
                {
                    String dir = System.getProperty("user.dir");
                    dir.replace("\\\\\\\\\\", "/");
                    try {
                    Runtime.getRuntime().exec("explorer " + dir + "\\Relatorios");
                    } catch (IOException ex) {
                    Logger.getLogger(TelaRelatorioLigacoes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                        } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioLigacoes.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioLigacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioLigacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioLigacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioLigacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaRelatorioLigacoes dialog = new TelaRelatorioLigacoes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtMesRelat;
    // End of variables declaration//GEN-END:variables
}
