/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.bean.Datas;
import model.bean.Ligacoes;
import model.bean.Limites;
import model.bean.clsDados;
import model.dao.LigacoesDAO;
import model.dao.LimitesDAO;

/**
 *
 * @author Camara
 */
public class TelaEditaLigacoes extends javax.swing.JDialog {
    /**
     * Creates new form TelaEditaLigacoes
     */
    public TelaEditaLigacoes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        clsDados clsDados1 = new clsDados();
        int idTable = clsDados1.getIdTable();
        
        //LIGACOES
        LigacoesDAO ligacoes = new LigacoesDAO();
        Ligacoes l = new Ligacoes();
        
        l.setId(idTable);
        int qtdadeLigacoes = ligacoes.buscaQuantidadeLigacoes(l);
        lblqtdadeLiga.setText(Integer.toString(qtdadeLigacoes));
        
        //Datas
        Datas datas = new Datas();
        String dataAtual = datas.getDataAtualHueBr();
        lblDataAt.setText(dataAtual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblqtdadeLiga = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDataAt = new javax.swing.JLabel();
        txtNumeroLigado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Quantidade de Ligações Realizadas :");

        lblqtdadeLiga.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        lblqtdadeLiga.setForeground(new java.awt.Color(102, 102, 102));

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jButton1.setText("Adicionar Ligação");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jButton2.setText("Remover Ligação");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Número Ligado :");

        jLabel4.setText("Data Atual :");

        lblDataAt.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDataAt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblqtdadeLiga))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroLigado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblqtdadeLiga))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtNumeroLigado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblDataAt))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clsDados clsDados2 = new clsDados();
        int idTable = clsDados2.getIdTable();
        
        LimitesDAO limites1 = new LimitesDAO();
        Limites li1 = new Limites();
        
        LigacoesDAO ligacoes1 = new LigacoesDAO();
        Ligacoes l1 = new Ligacoes();
        
        l1.setId(idTable);
        int qtdadeLigacoes = ligacoes1.buscaQuantidadeLigacoes(l1);
        
        int limiteLiga  = limites1.buscaLimiteLiga(li1);
        
        if(qtdadeLigacoes >= limiteLiga)
        {
            JOptionPane.showMessageDialog(null, "O usuário já realizou todas as ligações disponíveis", "Limite Excedido de " + limiteLiga + " Ligações", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
                Datas datas1 = new Datas();
                String dataBanco = datas1.getDataAtual();

                String numeroLigado = txtNumeroLigado.getText();
                if(numeroLigado.length() > 7)
                {            
                    l1.setDataLiga(dataBanco);
                    l1.setIdPerfil(idTable);
                    l1.setNumeroLigado(numeroLigado);
                    ligacoes1.create(l1);

                    this.dispose();
                    
                    TelaVerificaEdita telaVerificaEdita = new TelaVerificaEdita(null, rootPaneCheckingEnabled);
                    telaVerificaEdita.setVisible(true);
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Para executar uma ligação é necessário informar um número válido.");
                }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clsDados clsDados3 = new clsDados();
        int idTable = clsDados3.getIdTable();
        
        LigacoesDAO ligacoes = new LigacoesDAO();
        Ligacoes l = new Ligacoes();
        
        l.setId(idTable);
        int qtdadeLigaEf = ligacoes.buscaQuantidadeLigacoes(l);
        
        if(qtdadeLigaEf > 0)
        {
            LigacoesDAO ligacoes1 = new LigacoesDAO();
            Ligacoes l1 = new Ligacoes();

            l1.setIdPerfil(idTable);
            int ultimoIdLiga = ligacoes1.buscaUltimoIdLigacao(l1);
            l1.setId(ultimoIdLiga);

            ligacoes1.deletaLiga(l1);
            this.dispose();
            
            TelaVerificaEdita telaVerificaEdita = new TelaVerificaEdita(null, rootPaneCheckingEnabled);
            telaVerificaEdita.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Não existe ligação realizada !");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditaLigacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditaLigacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditaLigacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditaLigacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaEditaLigacoes dialog = new TelaEditaLigacoes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDataAt;
    private javax.swing.JLabel lblqtdadeLiga;
    private javax.swing.JTextField txtNumeroLigado;
    // End of variables declaration//GEN-END:variables
}
